/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Letter = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Text,
  'theme' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'from' : IDL.Text,
  'createdAt' : IDL.Int,
  'bouquet' : IDL.Text,
});

export const idlService = IDL.Service({
  'createLetter' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteLetter' : IDL.Func([IDL.Nat], [], []),
  'getLetter' : IDL.Func([IDL.Nat], [IDL.Opt(Letter)], ['query']),
  'getLetters' : IDL.Func([], [IDL.Vec(Letter)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Letter = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Text,
    'theme' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'from' : IDL.Text,
    'createdAt' : IDL.Int,
    'bouquet' : IDL.Text,
  });
  
  return IDL.Service({
    'createLetter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteLetter' : IDL.Func([IDL.Nat], [], []),
    'getLetter' : IDL.Func([IDL.Nat], [IDL.Opt(Letter)], ['query']),
    'getLetters' : IDL.Func([], [IDL.Vec(Letter)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };